name: ublox_gnss
description: Driver for the u-blox M* GNSS receivers.
environment:
  sdk: ^2.0.0-alpha.144
dependencies:
  gnss_location:
    url: github.com/toitware/toit-gnss-location
    version: ^1.1.0
  location:
    url: github.com/toitware/toit-location
    version: ^1.1.0
  ubx-message:
    path: ../ubx-message
