dependencies:
  gnss_location:
    url: github.com/toitware/toit-gnss-location
    version: ^1.1.0
  location:
    url: github.com/toitware/toit-location
    version: ^1.1.0
  ublox_gnss:
    path: ..
  ubx-message:
    path: ../../ubx-message
